### ISSUE TITLE
Can we replace `utils.Comparator` with the built-in `comparable`?

### ISSUE THREAD

**Issue by soulmachine** [mikekonan/gods-generic#1]
Hi Mike,

This is a suggestion instead of an issue.

I see that in these lines https://github.com/mikekonan/gods-generic/blob/main/tree/redblacktree/tree.go#L16-L19:

```go
type Tree[K any, V any] struct {
	Root       *Node[K, V]
	size       int
	Comparator utils.Comparator[K]
}
```

Is it possible to change to:

```go
type Tree[K comparable, V any] struct {
	Root       *Node[K, V]
	size       int
}
```

The `comparable` is a predeclared interface after Go 1.18.

After getting rid of `Comparator`,  the code looks cleaner, what do you think?

**Comment by mikekonan** [comment]
Hi. I agree with you, would you mind doing a PR?

**Comment by mikekonan** [comment]
Considered it again. Technically there is no reason to force users to use comparable types due there is no comparison between keys. Comparison in the comparator.

**Comment by soulmachine** [comment]
After careful consideration, I agree that `util.Comparator` is more user friendly than the built-in `comparable`, closing this issue now
